### ISSUE TITLE
Бот не запускается

### ISSUE THREAD

**Issue by n-burov** [MasterGroosha/telegram-casino-bot#3]
Добрый день! Выполнил установку бота Dice по инструкции, в консоли все запустилось, каких-либо ошибок нет, однако бот на какие-либо команды не реагирует
![2022-03-25_17-34-04](https://user-images.githubusercontent.com/17441016/160141329-dc793bab-ba26-4603-8476-c3b772e6488e.png)
.

**Comment by MasterGroosha** [comment]
`docker-compose logs` ?

**Comment by n-burov** [comment]
![2022-03-25_17-50-15](https://user-images.githubusercontent.com/17441016/160144368-1356e936-1e3d-48d6-952f-baa7a292472f.png)
Из настроек поменял только токен бота и выбрал image для ARM

**Comment by MasterGroosha** [comment]
Как минимум, вижу, что неправильный образ выбран. Raspberry Pi на ARM, а судя по ошибке, используется x86.
Покажите, какое значение стоит в переменной `image` в компоузе?

**Comment by n-burov** [comment]
![2022-03-25_17-55-25](https://user-images.githubusercontent.com/17441016/160145231-f593e117-99b1-4dbf-b5d8-f7a82e04d648.png)

**Comment by n-burov** [comment]
Что-то мне подсказывает, что пути в volumes тоже надо поменять?....

**Comment by MasterGroosha** [comment]
А какая именно Raspberry Pi?

**Comment by n-burov** [comment]
3b plus

**Comment by n-burov** [comment]
Могу конечно проверить на чем-то ином, но мне принципиально запустить это на малине🤔

**Comment by MasterGroosha** [comment]
У Raspberry Pi 3b+ архитектура не ARM64, а ARMv53. Так что эти образы не заведутся :(
https://amperka.ru/product/raspberry-pi-3-model-b-plus 

Можно собрать свой образ через buildx, но я сейчас не готов этим заняться. Предлагаю сделать это самостоятельно.

**Comment by left1n0dead** [comment]
Здравствуйте, совершенно не могу понять в чем дело, ни в какую не запускается, в конфигах менял лишь API token и версию образа на ARM64 (устройство: redmi note 7, kali linux  4.4.270 kernel)
![Screenshot_20220405-233747_Терминал](https://user-images.githubusercontent.com/88082697/161826382-9a7c93af-a3c9-4ac5-bc92-76caa249aceb.png)
![Screenshot_20220405-233753_Терминал](https://user-images.githubusercontent.com/88082697/161826390-b80806ae-47e4-4609-8b4f-b96f54bdfe33.png)
![Screenshot_20220405-233757_Терминал](https://user-images.githubusercontent.com/88082697/161826393-3bccc2f4-cc4c-486c-be81-de9b573602dc.png)
![Screenshot_20220405-233800_Терминал](https://user-images.githubusercontent.com/88082697/161826396-014e11be-9d45-45c2-8f56-f862c22c29db.png)

**Comment by MasterGroosha** [comment]
@left1n0dead как я понимаю, не установлен Docker, ну и в целом, не рекомендую использовать смартфон в качестве сервера

**Comment by left1n0dead** [comment]
Дак вот в том и проблема, судя по ошибке нет докера, а он установлен, также как и docker -compose

**Comment by left1n0dead** [comment]
Переустанавливать докер не помогло

**Comment by MasterGroosha** [comment]
С вопросами установки Docker на мобилки, пожалуйста, не сюда. Это костыль, которым изначально не надо пользоваться. Поберегите свои нервы и время.
