### ISSUE TITLE
aogram3.0.0b4 изменения

### ISSUE THREAD

**Issue by PhoenixNazarov** [MasterGroosha/telegram-casino-bot#4]
aogram3.0.0b2
https://github.com/MasterGroosha/telegram-casino-bot/blob/264d2fe78b9807a89f732842f8d9d58c477648e4/bot/__main__.py#L5-L6

aogram3.0.0b4
```python3
from aiogram.fsm.storage.memory import MemoryStorage
from aiogram.fsm.storage.redis import RedisStorage
```

**Comment by MasterGroosha** [comment]
Всё верно, в aiogram 3.0b4 есть [ломающие изменения](https://docs.aiogram.dev/en/dev-3.x/changelog.html#b4-2022-08-14), а в requirements.txt [зафиксирована](https://github.com/MasterGroosha/telegram-casino-bot/blob/aiogram3/requirements.txt#L2) версия 3.0b2

Как доберутся руки обновить до более свежей беты — сделаю.
